project:
  type: book
  output-dir: docs

book:
  title: A quarto book for technical documentations
  subtitle: A demonstration how quarto books can be used for documentation and collaboration
  date: today
  date-format: long
  author:
    - name: Damian Oswald
      affiliation: Federal Office for Agriculture FOAG
      orcid: 0009-0008-0658-7697
  abstract: This document presents a comprehensive demonstration of the versatile capabilities of Quarto books through a series of practical examples. By leveraging Quarto's robust markdown support, we illustrate how to seamlessly integrate emojis, construct informative tables, and create complex diagrams using Mermaid syntax.
  chapters:
    - index.qmd
    - demo.qmd
    - last.qmd
  repo-url: https://github.com/damian-oswald/wiki-test
  repo-actions: [source, issue]
  page-footer:
    border: true
    left: © 2023, Damian Oswald
    right: 
    - icon: github
      href: https://github.com/Damian-Oswald/wiki-test
    - icon: envelope-fill
      href: mailto:damian.oswald@protonmail.com
  sharing: [twitter, linkedin]
  comments:
    hypothesis:
      theme: clean
      openSidebar: false
    
format:
  html:
    theme: [cosmo, theme.scss]
    mermaid-theme: neutral
